### ISSUE TITLE
Could not locate repository

### ISSUE THREAD

**Issue by notscottthompson** [vercel/next-learn-starter#27]
Trying to follow the tutorial here: 

https://nextjs.org/learn/basics/create-nextjs-app/setup

I can't get past the first step "Create a Next.js app". 

Tried running the following command: 
`npx create-next-app nextjs-blog --use-npm --example "https://github.com/vercel/next-learn-starter/tree/master/learn-starter"`

I get the following error: 
`Could not locate the repository for "https://github.com/vercel/next-learn-starter/tree/master/learn-starter". Please check that the repository exists and try again.`

**Comment by leerob** [comment]
Hey! Thanks for opening an issue.

My guess is this was due to an intermittent connection issue with GitHub. I'm going to close this.

Could you please try again? If the issue persists, I'm happy to re-open and investigate further 🕵️

**Comment by anasanzari** [comment]
@leerob still happening

**Comment by curly210102** [comment]
Because the request of https://api.github.com reached the rate limit. create-next-app request api.github.com to check repo exists([SourceCode](https://github.com/vercel/next.js/blob/caca389cc1b0f5df43128750097844a5dcadf320/packages/create-next-app/create-app.ts#L75))

Quote from [github doc](https://docs.github.com/en/rest/overview/resources-in-the-rest-api#rate-limiting):
> For unauthenticated requests, the rate limit allows for up to 60 requests per hour. Unauthenticated requests are associated with the originating IP address, and not the user making requests.

You can query remaining ratelimit of your IP by `curl -I https://api.github.com/users/octocat`. The best solution is using Basic Authentication or OAuth, unfortunately create-next-app doesn't recognize the auth parameter yet. Thus, maybe have to wait until the ratelimit reset.

@leerob When upper to the rate limit, how about giving a message and works with auth, or ignore the check process just download the repo/example.

**Comment by arahansen** [comment]
I've also started running into this:

```
create-next-app --example https://github.com/trpc/trpc --example-path examples/next-prisma-starter-websockets trpc-prisma-starter-websockets
Could not locate the repository for "https://github.com/trpc/trpc". Please check that the repository exists and try again.
```

Example from [this repo](https://github.com/trpc/trpc/tree/main/examples/next-prisma-websockets-starter)

**Comment by friari** [comment]
Has anyone found a solution to this? I'm also getting a message saying it could not locate the repository. When I ran `curl -I https://api.github.com/users/octocat` it shows that 

`x-ratelimit-limit: 60
x-ratelimit-remaining: 59
x-ratelimit-reset: 1707178711
x-ratelimit-resource: core
x-ratelimit-used: 1`

**Comment by slelas** [comment]
Can confirm it works after waiting for a bit.

A few minutes earlier:
```
x-ratelimit-limit: 60
x-ratelimit-remaining: 0
x-ratelimit-reset: 1708045637
```

Now:
```
x-ratelimit-limit: 60
x-ratelimit-remaining: 59
x-ratelimit-reset: 1708049430
```

**Comment by oilandrust** [comment]
This is not solved and the problem remains.

**Comment by fdterr** [comment]
Still having this issue...

**Comment by jmknighten9** [comment]
Also getting this issue
